name: Pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:

      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Print Java version
        run: java -version

      - name: Print Maven version
        run: mvn -version

      - name: Compile
        run: mvn clean --batch-mode compile

      - name: Test
        run: mvn --batch-mode test